apiVersion: v1
kind: Pod
metadata:
  name: a-hi
  labels:
    app: balance_label
spec:
  containers:
    - image: nginx-mysql
      name: nginx-container-ahi
      imagePullPolicy: IfNotPresent # Always / Never
      ports:
        - containerPort: 80
  # restartPolicy: OnFailure
